### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by freder** [TooTallNate/node-bindings#17]
hi,

[I am cross-posting this](https://github.com/sindresorhus/gulp-mocha/issues/86), because it is unclear to me where exactly this error originates from. but it looks like it has s.th. to do with wither `gulp-mocha` or `node-bindings`, or a combination.

error:

```
[...]

[12:35:24] Starting 'mocha'...
[12:35:24] 'mocha' errored after 35 ms
[12:35:24] Error in plugin 'gulp-mocha'
Message:
    Module did not self-register.
Stack:
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Volumes/Macintosh HD 2/Projects/project/code/project.js/node_modules/libxmljs/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Volumes/Macintosh HD 2/Projects/project/code/project.js/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

full info [over at gulp-mocha](https://github.com/sindresorhus/gulp-mocha/issues/86).

**Comment by HashanP** [comment]
I got the same error using `node-bindings` from `node-ogg`.

**Comment by chrisdopuch** [comment]
I also got the same error using `node-bindings` from `node-segfault-handler`

**Comment by HashanP** [comment]
Try deleting all your dependencies and reinstalling them, that worked for me. I think the native dependencies had to be recompiled for node 0.12.

**Comment by chrisdopuch** [comment]
Thanks HashanP that worked for me too

**Comment by tecfu** [comment]
@HashanP That was exactly correct. Thanks.

**Comment by kumavis** [comment]
Had this problem on a fresh install on Modulus hosting
