### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by baslr** [TooTallNate/node-bindings#21]
bindings can't find the bin, but its there.
node v4-2-2, bcrypt v0.8.5
```
app-0 (err): Error: Could not locate the bindings file. Tried:
app-0 (err):  → /backend/node_modules/bcrypt/build/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/build/Debug/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/build/Release/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/out/Debug/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/Debug/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/out/Release/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/Release/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/build/default/bcrypt_lib.node
app-0 (err):  → /backend/node_modules/bcrypt/compiled/4.2.2/linux/x64/bcrypt_lib.node
app-0 (err):     at bindings (/backend/node_modules/bindings/bindings.js:88:9)
app-0 (err):     at Object.<anonymous> (/backend/node_modules/bcrypt/bcrypt.js:3:35)
app-0 (err):     at Module._compile (module.js:435:26)
app-0 (err):     at Object.Module._extensions..js (module.js:442:10)
app-0 (err):     at Module.load (module.js:356:32)
app-0 (err):     at Function.Module._load (module.js:311:12)
app-0 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
app-0 (err):     at Module.require (module.js:366:17)
app-0 (err):     at require (module.js:385:17)
app-0 (err):     at Object.<anonymous> (/backend/lib/authentication.js:21:14)

$ ls -l node_modules/bcrypt/build/Release/bcrypt_lib.node
-rwxr-xr-x 1 vagrant vagrant 63653 Dec  2 12:58 node_modules/bcrypt/build/Release/bcrypt_lib.node

**Comment by hajarghaem** [comment]
How to fix it?

**Comment by cztomsik** [comment]
This error is also shown if there was any runtime error during module load (and such error is silently ignored which is bad IMHO)
