### ISSUE TITLE
Webpack Issues

### ISSUE THREAD

**Issue by brodo** [TooTallNate/node-bindings#25]
Hi,
when using [webpack](https://webpack.github.io/) with this package, two warnings occure:

```
WARNING in ./~/bindings/bindings.js
Critical dependencies:
76:22-40 the request of a dependency is an expression
76:43-53 the request of a dependency is an expression
 @ ./~/bindings/bindings.js 76:22-40 76:43-53

WARNING in ./~/bindings/README.md
Module parse failed: /path/to/my/app/node_modules/bindings/README.md Unexpected token (2:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:3)
    at Parser.pp.raise (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.parseExprAtom (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOp (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:171:41)
    at Parser.pp.parseExprOp (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:173:19)
    at Parser.pp.parseExprOps (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:153:15)
    at Parser.pp.parseMaybeConditional (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/path/to/my/app/node_modules/webpack/node_modules/acorn/dist/acorn.js:110:19)
 @ ./~/bindings ^\.\/.*$
```

The first complains about dynamic imports. [The webpack guys think that they should not be used at all](https://github.com/webpack/webpack/issues/196#issuecomment-71917456). I don't know if that is even possible in this case. The second one obviously is webpack trying to parse the readme for some reason 😄 .

**Comment by brodo** [comment]
After looking into it, there seems to be no way to fix it from your side..

**Comment by TooTallNate** [comment]
This module is for loading native C++ addons, which wouldn't be supported on the client-side anyways. What are you trying to use this module via webpack for?

**Comment by brodo** [comment]
I'm building an Electron app and I use webpack as  my one and only transpilation, hot-reloading etc. tool. So in my node-code I can do fancy stuff like this:

```javascript
import { Readable } from 'stream';
```

**Comment by timwis** [comment]
FYI, I ran into this too...not sure what to do

**Comment by aft-luke** [comment]
@brodo did you open an issue elsewhere to resolve this? I'm getting the same issue too but cannot figure out why.

**Comment by brodo** [comment]
@aft-luke https://github.com/rwaldron/johnny-five/issues/1101#issuecomment-213581938

**Comment by anhldbk** [comment]
@brodo You made my day! # # @

**Comment by akrueger** [comment]
It wasn't quite clear to me what the resolution was on this. Did you end up externally loading bindings.js outside of the bundle? I have managed to calm webpack down, but not to successfully load bindings.js as a dependency for other modules inside the bundle.
