### ISSUE TITLE
Debian, Node v6: Could not locate the bindings file 

### ISSUE THREAD

**Issue by jadbox** [TooTallNate/node-bindings#26]
I'm not sure if this is an issue with deasync or node-bindings with Node v6.

The deasync issue is here: https://github.com/abbr/deasync/issues/58

`````` /usr/src/app/node_modules/bindings/bindings.js:88
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/src/app/node_modules/deasync/build/deasync.node
 → /usr/src/app/node_modules/deasync/build/Debug/deasync.node
 → /usr/src/app/node_modules/deasync/build/Release/deasync.node
 → /usr/src/app/node_modules/deasync/out/Debug/deasync.node
 → /usr/src/app/node_modules/deasync/Debug/deasync.node
 → /usr/src/app/node_modules/deasync/out/Release/deasync.node
 → /usr/src/app/node_modules/deasync/Release/deasync.node
 → /usr/src/app/node_modules/deasync/build/default/deasync.node
 → /usr/src/app/node_modules/deasync/compiled/6.0.0/linux/x64/deasync.node
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:88:9)
    at /usr/src/app/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/usr/src/app/node_modules/deasync/index.js:76:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)

npm info lifecycle rules-worker@0.0.38~start: Failed to exec start script
npm ERR! Linux 4.4.5-15.26.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE```
``````

**Comment by TooTallNate** [comment]
Did you get this sorted out in https://github.com/abbr/deasync/issues/58 ?

Gonna close this issue. Open a new one if you still feel there's an issue with this module.
