### ISSUE TITLE
Node v7: Could not locate the bindings file

### ISSUE THREAD

**Issue by TOP-Chao** [TooTallNate/node-bindings#31]
```
/usr/local/lib/node_modules/pm2-web/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/Debug/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/Release/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/out/Debug/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/Debug/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/out/Release/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/Release/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/build/default/binding.node
 → /usr/local/lib/node_modules/pm2-web/node_modules/pwuid/compiled/7.5.0/darwin/x64/binding.node
    at bindings (/usr/local/lib/node_modules/pm2-web/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2-web/node_modules/pwuid/index.js:2:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2-web/server/components/Configuration.js:5:10)
```

**Comment by TooTallNate** [comment]
This generally means that the compiled C++ portion of the module you are using did not get there successfully.

However, this is not a problem with this module itself, but of one that uses this module. You should create an issue on the [`pm2-web` issue tracker](https://github.com/achingbrain/pm2-web) to see what they think.
