### ISSUE TITLE
Error: The specified module could not be found. But the file Exists

### ISSUE THREAD

**Issue by soyFerrero** [TooTallNate/node-bindings#35]
The file exists.  Any idea how to fix it?

```
> > node-iohook@0.0.1 test E:\node-iohook
> > node test.js "config"
> 
> E:\node-iohook\node_modules\bindings\bindings.js:83
>         throw e
>         ^
> 
> Error: The specified module could not be found.
> \\?\E:\node-iohook\build\Release\node-iohook.node
>     at Error (native)
>     at Object.Module._extensions..node (module.js:568:18)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)
>     at Function.Module._load (module.js:407:3)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at bindings (E:\node-iohook\node_modules\bindings\bindings.js:76:44)
>     at Object.<anonymous> (E:\node-iohook\test.js:1:104)
>     at Module._compile (module.js:541:32)
>  npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-iohook@0.0.1 test: `node test.js "config"`
> npm ERR! Exit status 1
```

**Comment by soyFerrero** [comment]
It fixed up!. The file did not have access.
regards

**Comment by wesselviljoen** [comment]
@soyFerrero How did you manage to allow the process to access the file? Having the same problem but can't seem to find a fix. Also using node-iohook...

**Comment by maxerbox** [comment]
I'm wondering the same thing, how to allow the process to access the file (I'm on Windows).
I'm encountering this issue with bluetooth-serial-port

**Comment by Yongle-Fu** [comment]
use electron-builder run on some Windows 10 encountering this issue
