### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 59.

### ISSUE THREAD

**Issue by maartenvandewaarsenburg** [TooTallNate/node-bindings#47]
Bindings was introduced by using inotify. A test program I've made in the same project, using only inotify, works without problems.

When I start my node/express application I get the following error.
```
~/workspace/adoc2html/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Module version mismatch. Expected 48, got 59.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/VERUM.COM/maartenvandewaarsenb/workspace/adoc2html/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/VERUM.COM/maartenvandewaarsenb/workspace/adoc2html/node_modules/inotify/inotify.js:1:99)
    at Module._compile (module.js:570:32)
maartenvandewaarsenb@vpce020:~/workspace/adoc2html$
```
I'm using node v9.2.0 and npm 5.8.0 on Ubuntu 17.10.

I've rebuilt (npm install) node_modules from scratch (tried yarn as well) but I keep getting this error.

How should I proceed to get it working?

**Comment by maartenvandewaarsenburg** [comment]
**Problem solved.**
My npm start script in package,json was pointing to an older (6.x.x) version of node.
