### ISSUE TITLE
Error handling seems buggy on OS using an other language (not english)

### ISSUE THREAD

**Issue by Skywalker13** [TooTallNate/node-bindings#48]
![image](https://user-images.githubusercontent.com/397862/39465591-7076ce94-4d24-11e8-9a07-cef1fbb3eab1.png)

~~`/not find/i` seems related to `"est introuvable"` in french...~~ because this bug, I can not load native modules on Windows 7 French like `better-sqlite3`.

I think that you try to parse
```
$ node
> require('a')
Error: Cannot find module 'a'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

OK.. maybe it's an electron bug.. in the screenshot, I try to load the module with electron

**Comment by Skywalker13** [comment]
My bad...
