### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by thisTom** [TooTallNate/node-bindings#57]
PS F:\www\zuhao\client> yarn debug:main 
yarn run v1.13.0
$ electron --inspect=5858 -w ./dist/main/main.js

 Debugger listening on ws://127.0.0.1:5858/0977f6ec-8de8-4e54-a2d5-09ad8d82aabe
For help, see: https://nodejs.org/en/docs/inspector
App threw an error during load
TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (F:\www\zuhao\client\dist\main\main.js:139:211412)
    at t (F:\www\zuhao\client\dist\main\main.js:139:210566)
    at Object.<anonymous> (F:\www\zuhao\client\dist\main\main.js:1:74523)
    at a (F:\www\zuhao\client\dist\main\main.js:1:110)
    at Object.<anonymous> (F:\www\zuhao\client\dist\main\main.js:223:156632)
    at a (F:\www\zuhao\client\dist\main\main.js:1:110)
    at Object.<anonymous> (F:\www\zuhao\client\dist\main\main.js:139:219468)
    at a (F:\www\zuhao\client\dist\main\main.js:1:110)
    at F:\www\zuhao\client\dist\main\main.js:1:902
    at Object.<anonymous> (F:\www\zuhao\client\dist\main\main.js:1:913)

when i package electron ，has this error。 thanks for you help，realy need help

**Comment by zygzagZ** [comment]
#50

**Comment by petertorelli** [comment]
I'm facing this too. Try commenting out the return when `calling_file` is undefined (because it is by default):
~~~
  Error.prepareStackTrace = function(e, st) {
    for (var i = 0, l = st.length; i < l; i++) {
      fileName = st[i].getFileName();
      if (fileName !== __filename) {
        if (calling_file) {
          if (fileName !== calling_file) {
            return;
          }
        } else {
          //return;
        }
      }
    }
  };
~~~
